modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="BouncingElf10"
description='''
Adds pushing to Sable: Ragdolls
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable_player_ragdoll"
    type="required"
    reason="Provides the RagdollAPI used to launch pushed players and mobs."
    versionRange="${sable_ragdoll_version_range}"
    ordering="AFTER"
    side="BOTH"
